service: API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: dev
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  getCompanies:
    handler: index.getCompanies
    events:
      - httpApi:
          path: /companies
          method: get

  getCompaniesByID:
    handler: index.getCompaniesByID
    events:
      - httpApi:
          path: /companiesid/{id}
          method: get
  
  createCompany:
    handler: index.createCompany
    events:
      - httpApi:
          path: /createcompany
          method: post
  
  editCompanyDetails:
    handler: index.editCompanyDetails
    events:
      - httpApi:
          path: /editcompanydetails/{id}
          method: put

  archiveCompany:
    handler: index.archivedCompanies
    events:
      - httpApi:
          path: /archivedCompanies/{id}
          method: put
  
  teamByCompany:
    handler: index.getTeamByCompany
    events:
      - httpApi:
          path: /getTeamByCompany/{id}
          method: get

  getTeamByID:
    handler: index.getTeamByID
    events:
      - httpApi:
          path: /getTeamByID/{id}
          method: get
  
  createTeamforSpecificCompanyID:
    handler: index.createTeamforSpecificCompanyID
    events:
      - httpApi:
          path: /createTeamforSpecificCompanyID/{id}
          method: post
  
  editTeamDetails:
    handler: index.editTeamDetails
    events:
      - httpApi:
          path: /editTeamDetails/{id}
          method: post

  archiveTeam:
    handler: index.archiveTeam 
    events:
      - httpApi:
          path: /archiveTeam/{id}
          method: put
  
  getAllEmployeeByCompany:
    handler: index.getAllEmployeeByCompany 
    events:
      - httpApi:
          path: /getAllEmployeeByCompany/{company_name}
          method: get